@host = http://127.0.0.1:{{$dotenv PORT}}
@id = 1

# Add author endpoint
POST {{host}}/authors
Content-Type: application/json

{
   "name": "",
   "description": ""
}

###

# Get all authors endpoint
GET {{host}}/authors

###

# Get single author endpoint
GET {{host}}/authors/{{id}}

###

# Delete author endpoint
DELETE {{host}}/authors/{{id}}

###

# Update author endpoint
PATCH {{host}}/authors/{{id}}
Content-Type: application/json

{
   "name": "",
   "description": ""
}
