@host = http://127.0.0.1:{{$dotenv PORT}}
@isbn = 978-3-16-148410-0

# Add book endpoint
POST {{host}}/books
Content-Type: application/json

{
   "isbn": "{{isbn}}",
   "title": "",
   "subject": "",
   "publisher": "",
   "language": "",
   "number_of_pages": 7
}

###

# Get all books endpoint
GET {{host}}/books

###

# Get single book endpoint
GET {{host}}/books/{{isbn}}

###

# Delete book endpoint
DELETE {{host}}/books/{{isbn}}

###

# Update book endpoint
PATCH {{host}}/books/{{isbn}}
Content-Type: application/json

{
   "isbn": "{{isbn}}",
   "title": "",
   "subject": "",
   "publisher": "",
   "language": "",
   "number_of_pages": 7
}
