@host = http://127.0.0.1:{{$dotenv PORT}}

# Add book endpoint
POST {{host}}/books
Content-Type: application/json

{
   "isbn": "",
   "title": "",
   "subject": "",
   "publisher": "",
   "language": "",
   "number_of_pages": 7
}

###

# Get all books endpoint
GET {{host}}/books
